remove redundant props from ActionableInput
aserto-dev/aserto-react-components pull request #80
Opened 2021-12-20 21:01 UTC by ananyakaushik

Addresses the bug where clicking the hide/show button does nothing. Also this starts to phase out Actionable Inputs altogether

2021-12-20 22:48 UTC, authereal requested changes
The copy button doesn't seem to work for me anymore
http://localhost:6006/?path=/story/common-actionableinput--primary-with-copy

2021-12-20 22:51 UTC, ananyakaushik commented
> The copy button doesn't seem to work for me anymore http://localhost:6006/?path=/story/common-actionableinput--primary-with-copy

@authereal `onClickCopy` expects a function to be passed in

2021-12-20 23:52 UTC, TheRealPiotrP approved these changes

2021-12-21 00:07 UTC, authereal approved these changes

2021-12-21 00:07 UTC, merged

2021-12-21 00:08 UTC, authereal commented
https://www.npmjs.com/package/@aserto/aserto-react-components/v/7.3.3